## Theory

vectors and matrices in NumPy

In [1]:
import numpy as np

In [3]:
x = np.random.normal(loc = 1, scale = 10, size = (1000, 50))
print x

[[  5.40142583  22.39260449   8.55903365 ...,  -3.44621456   3.46907754
    7.76830996]
 [ 15.79155008  -1.12127586  -3.27252342 ...,  -6.78715835  17.01855798
    8.96655821]
 [ -0.20664798  15.8515979   -2.12237576 ...,   3.8822773   -7.29763711
   23.13900315]
 ..., 
 [ 10.09172641   6.78313103   7.22585949 ..., -11.43266173   9.85632309
   -9.5691101 ]
 [-14.38907639   1.2267644   23.55616835 ...,  -2.62055319   0.91100018
   -9.27802839]
 [ -6.06213217   9.03447416   2.55765585 ...,   2.56132509   9.73940764
   -9.18893855]]


In [4]:
m = np.mean(x, axis = 0)
s = np.std(x, axis = 0)
x_norm = (x - m) / s
print x_norm

[[ 0.42724982  2.17054007  0.70306778 ..., -0.42614236  0.26305693
   0.71444379]
 [ 1.45341029 -0.18473206 -0.47765095 ..., -0.76398771  1.59354825
   0.83907315]
 [-0.12662071  1.51535895 -0.36287308 ...,  0.31493474 -0.79418069
   2.31314392]
 ..., 
 [ 0.89047826  0.60701431  0.57002496 ..., -1.23375369  0.89025255
  -1.08881488]
 [-1.52732074  0.05045983  2.19969226 ..., -0.34264923  0.01186651
  -1.05853958]
 [-0.70492625  0.8325205   0.10416612 ...,  0.18135645  0.87877204
  -1.04927338]]


In [7]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
sums = np.sum(Z, axis = 1)
print np.nonzero(sums > 10)

(array([1, 4, 5]),)


In [10]:
a = np.eye(3)
b = np.eye(3)
print a
print b

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [12]:
ab = np.vstack((a, b))
print ab

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Data preprocessing in Pandas

In [2]:
import pandas
data = pandas.read_csv('titanic.csv', index_col = 'PassengerId')
print data

             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   
16                  1       2   
17                  0       3   
18                  1       2   
19                  0       3   
20                  1       3   
21                  0       2   
22                  1       2   
23                  1       3   
24                  1       1   
25                  0       3   
26                  1       3   
27                  0       3   
28                  0       1   
29        

In [17]:
print data['Sex'].value_counts() # количество мужчин и женщин

male      577
female    314
Name: Sex, dtype: int64


In [23]:
print 1. * len(data[data.Survived == 1]) / len(data) * 100 # percent of survived

38.3838383838


In [24]:
print 1. * len(data[data.Pclass == 1]) / len(data) * 100 # percent of 1st class

24.2424242424


In [38]:
print data['Age'].mean()
print data['Age'].median()

29.6991176471
28.0


In [26]:
print data.corr(method='pearson')['Parch']['SibSp'] # pearson corr between Parch and SibSp

0.41483769862


In [3]:
all_names = data[data.Sex == 'female']['Name']
# print all_names
d = dict()
for name in all_names:
    s = name.split()
    cur_name = ''
    if 'Mrs.' in s and '(' in name:
        cur_name = name.split('(')[1].split()[0]
    else:
        cur_name = s[2]
    if cur_name in d:
        d[cur_name] += 1
    else:
        d[cur_name] = 1
ans = 0
s = ''
for k in d.keys():
    if d[k] > ans:
        ans = d[k]
        s = k
print s # most common name

Anna
